### ISSUE TITLE
Controller and Module are deprecated

### ISSUE THREAD

**Issue by paulfalgout** [hegdeashwin/learning-backbone-marionette#8]
I know these sections aren't flushed out, but if a tutorial is to be written, it should likely simply suggest not to use them.

**Comment by hegdeashwin** [comment]
Yes! @paulfalgout 
I really appreciated for that update @paulfalgout ... I used Marionette around 2 years long back. I am too updating myself with latest version but there are lots of projects which I have seen where they are still using old version and not migrated to latest version, I believe it will take some more time ... 

So though of keeping the deprecated methods as a examples by specifying [Deprecated] -> Providing the reason why they are deprecated and finally showing them the replacements for deprecated methods/approaches ... this way developers will understand in much better way [Cover all old and new version users]

Well! you can always guide me on this. I would be really thankful for your guidance.
